package ALumni;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import Connection.Database;
import beanclasses.JobBean;
import package1.EmailValidation;
import package1.Signin;

import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import javax.swing.Action;
import javax.swing.ButtonGroup;

import java.awt.event.ActionListener;
import java.sql.SQLException;


/**
 *
 * @author MUKUL
 */
public class JobPost extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public JobPost() {
    	setResizable(true);
    	setClosable(true);
    	setBorder(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ ButtonGroup g1=new ButtonGroup();
             
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        company = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        checkbox_full = new javax.swing.JCheckBox();
        checkbox_intern = new javax.swing.JCheckBox();
        checkbox_work = new javax.swing.JCheckBox();
        checkbox_part = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        loc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        link = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Company Name * ");

        jLabel2.setText("Job Title * ");

        checkbox_full.setText("Full Time");

        checkbox_intern.setText("Internship");

        checkbox_work.setText("Work from home");

        checkbox_part.setText("Part Time");

        jLabel3.setText("Role *");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Developer", "Tester", "Business head", "Data Scientist", "Audit", "CA" }));

        jLabel4.setText("Expected Salary (per Annum)");

        jLabel6.setText("Job Location *");

        jLabel7.setText("Google Form *");
        
        JButton btnNewButton = new JButton("Post");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		  EmailValidation ed=new EmailValidation();
        		if(!checkbox_full.isSelected()&&!checkbox_part.isSelected()&&!checkbox_work.isSelected()&&!checkbox_intern.isSelected()) {
        			JOptionPane.showMessageDialog(new JFrame(),"Select the job title");
        		}
        		else if(company.getText().equals("")||loc.getText().equals("")||link.getText().equals("")) {
        					JOptionPane.showMessageDialog(new JFrame(),"Fill all Values");
            		
        		}else if(!ed.isnumber(salary.getText())) {
        			JOptionPane.showMessageDialog(new JFrame(),"Experience and Salary can only be Integers");
        		}
        		else {
					
					  String name=company.getText(); String jobtitle=null;
					  if(checkbox_full.isSelected()) { jobtitle="Full Time"; } else
					  if(checkbox_part.isSelected()) { jobtitle="Part Time"; } else
					  if(checkbox_work.isSelected()) { jobtitle="Work from home"; } else
					  if(checkbox_intern.isSelected()) { jobtitle="Internship"; }
					
					  String salry=salary.getText();
					  String
					  location= loc.getText(); String joblink =link.getText(); 
					  String jobrole=jComboBox.getSelectedItem().toString();
					 JobBean jb=new JobBean();
					 jb.setName(name);
					 jb.setRole(jobrole);
					 jb.setJobTitle(jobtitle);
					 jb.setSalary(salry);
				
					 jb.setLocation(location);
					 jb.setLink(joblink);
					 jb.setEmail(Signin.email.getText());
					 try {
						Database db=new Database();
						db.Alumnijob(jb);
						company.setText("");
						loc.setText("");link.setText("");
						g1.clearSelection();
						
						
					} catch (SQLException e) {
						
					}
					 
					 
					 
					  
					  
					
					  
        		
        	}
        }});
       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2)
        				.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(layout.createSequentialGroup()
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(jLabel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(checkbox_full, Alignment.LEADING))
        						.addGap(18)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addGroup(layout.createSequentialGroup()
        								.addComponent(checkbox_intern)
        								.addGap(38)
        								.addComponent(checkbox_work)
        								.addGap(48)
        								.addComponent(checkbox_part))
        							.addComponent(company, GroupLayout.PREFERRED_SIZE, 359, GroupLayout.PREFERRED_SIZE)))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel4)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(28)
        							.addComponent(salary, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)))
        					.addGroup(layout.createSequentialGroup()
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(jLabel7, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel6, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addGap(45)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(loc, GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        							.addComponent(link)))))
        			.addContainerGap(47, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(424))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(193)
        			.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(48)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(company, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel2)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(checkbox_full)
        				.addComponent(checkbox_intern)
        				.addComponent(checkbox_work)
        				.addComponent(checkbox_part))
        			.addGap(18)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jComboBox, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addComponent(jLabel4)
        			.addGap(18)
        			.addComponent(salary, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(loc, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addComponent(link, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
        			.addGap(29)
        			.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        );
       
        g1.add(checkbox_full);
        g1.add(checkbox_full);
        g1.add(checkbox_work);
        g1.add(checkbox_part);
        g1.add(checkbox_intern);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        
    private javax.swing.JCheckBox checkbox_full;
    private javax.swing.JCheckBox checkbox_intern;
    private javax.swing.JCheckBox checkbox_part;
    private javax.swing.JCheckBox checkbox_work;
    private javax.swing.JTextField company;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField link;
    private javax.swing.JTextField loc;
    private javax.swing.JTextField salary;
    private final Action action = new SwingAction();
	private class SwingAction extends AbstractAction {
		public SwingAction() {
			putValue(NAME, "SwingAction");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
		}
	}
}
