package student;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import Connection.Database;
import beanclasses.JobBean;
import package1.EmailValidation;
import package1.Signin;

import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import javax.swing.Action;
import javax.swing.ButtonGroup;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JTable;
import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;


/**
 *
 * @author MUKUL
 */
public class JobPost extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public JobPost() {
    	getContentPane().setBackground(SystemColor.activeCaption);
    	setTitle("Search Jobs");
    	setResizable(true);
    	setClosable(true);
    	setBorder(null);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ ButtonGroup g1=new ButtonGroup();
             
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        checkbox_full = new javax.swing.JCheckBox();
        checkbox_intern = new javax.swing.JCheckBox();
        checkbox_work = new javax.swing.JCheckBox();
        checkbox_part = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        JScrollPane s=new JScrollPane();
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Job Title * ");

        checkbox_full.setText("Full Time");

        checkbox_intern.setText("Internship");

        checkbox_work.setText("Work from home");

        checkbox_part.setText("Part Time");

        jLabel3.setText("Role *");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Developer", "Tester", "Business head", "Data Scientist", "Audit", "CA" }));
        JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(10, 174, 584, 328);
		getContentPane().add(scrollPane);
		
		table = new JTable();
		scrollPane.setViewportView(table);
		
		
		
		model=new DefaultTableModel();
		Object[] column = {"Company Name","Location","Salary","Link","Posted By"};
		Object[] row=new Object[5];
		model.setColumnIdentifiers(column);
		model.setColumnIdentifiers(column);
		table.setModel(model);
        JButton btnNewButton = new JButton("Search");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		JobBean jb=new JobBean();
        		String jobtitle = null;
        		  if(checkbox_full.isSelected()) { jobtitle="Full Time"; } else
					  if(checkbox_part.isSelected()) { jobtitle="Part Time"; } else
					  if(checkbox_work.isSelected()) { jobtitle="Work from home"; } else
					  if(checkbox_intern.isSelected()) { jobtitle="Internship"; }
					  else {
						  JOptionPane.showMessageDialog(new JFrame(),"Select job title");
						  checkbox_full.setSelected(true);
					  }
					jb.setJobTitle(jobtitle);
					  String jobrole=jComboBox.getSelectedItem().toString();
					  jb.setRole(jobrole);
					  try {
					  Database db=new Database();
					ArrayList<ArrayList<String>>l=db.Studentjob(jb);  
				for(ArrayList<String> n: l) {
					row[0]=n.get(0);
					row[1]=n.get(1);
					row[2]=n.get(2);
					row[3]=n.get(3);
					row[4]=n.get(4);
				model.addRow(row);	
				}}catch(Exception e) {
						  e.printStackTrace();
					  }
					  
					  
					  
					  
					  
					
        	}
        });
       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jComboBox, 0, 168, Short.MAX_VALUE)
        					.addGap(249))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(30)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        					.addGap(285)))
        			.addGap(187))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel2)
        					.addContainerGap(552, Short.MAX_VALUE))
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(checkbox_full)
        					.addPreferredGap(ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
        					.addComponent(checkbox_intern)
        					.addGap(63)
        					.addComponent(checkbox_work)
        					.addGap(87)
        					.addComponent(checkbox_part)
        					.addGap(24))))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(233)
        			.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(15)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jComboBox, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(checkbox_part)
        				.addComponent(checkbox_work)
        				.addComponent(checkbox_intern)
        				.addComponent(checkbox_full))
        			.addGap(18)
        			.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(339, Short.MAX_VALUE))
        );
       
        g1.add(checkbox_full);
        g1.add(checkbox_full);
        g1.add(checkbox_work);
        g1.add(checkbox_part);
        g1.add(checkbox_intern);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        
    private javax.swing.JCheckBox checkbox_full;
    private javax.swing.JCheckBox checkbox_intern;
    private javax.swing.JCheckBox checkbox_part;
    private javax.swing.JCheckBox checkbox_work;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public DefaultTableModel model;
    private javax.swing.JTable table;}
  



